-- Add AUTO_INCREMENT to all id columns that extend BaseModel
-- Note: Cart and CartItem already have AUTO_INCREMENT from V3

-- Drop foreign key constraints that reference the id columns we're modifying
ALTER TABLE product DROP FOREIGN KEY FK_PRODUCT_ON_CATEGORY;
ALTER TABLE orders DROP FOREIGN KEY FK_ORDERS_ON_USER;
ALTER TABLE cart DROP FOREIGN KEY FK_CART_ON_USER;
ALTER TABLE password_reset_token DROP FOREIGN KEY FK_PASSWORD_RESET_TOKEN_ON_USER;
ALTER TABLE order_item DROP FOREIGN KEY FK_ORDER_ITEM_ON_PRODUCT;
ALTER TABLE cart_item DROP FOREIGN KEY FK_CART_ITEM_ON_PRODUCT;
ALTER TABLE order_item DROP FOREIGN KEY FK_ORDER_ITEM_ON_ORDER;
ALTER TABLE payment DROP FOREIGN KEY FK_PAYMENT_ON_ORDER;
ALTER TABLE cart_item DROP FOREIGN KEY FK_CART_ITEM_ON_CART;

-- Modify id columns to add AUTO_INCREMENT
ALTER TABLE category MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE product MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `user` MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE orders MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE order_item MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE payment MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE password_reset_token MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

-- Recreate foreign key constraints
ALTER TABLE product ADD CONSTRAINT FK_PRODUCT_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES category (id);
ALTER TABLE orders ADD CONSTRAINT FK_ORDERS_ON_USER FOREIGN KEY (user_id) REFERENCES `user` (id);
ALTER TABLE cart ADD CONSTRAINT FK_CART_ON_USER FOREIGN KEY (user_id) REFERENCES `user` (id);
ALTER TABLE password_reset_token ADD CONSTRAINT FK_PASSWORD_RESET_TOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES `user` (id);
ALTER TABLE order_item ADD CONSTRAINT FK_ORDER_ITEM_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);
ALTER TABLE cart_item ADD CONSTRAINT FK_CART_ITEM_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);
ALTER TABLE order_item ADD CONSTRAINT FK_ORDER_ITEM_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);
ALTER TABLE payment ADD CONSTRAINT FK_PAYMENT_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);
ALTER TABLE cart_item ADD CONSTRAINT FK_CART_ITEM_ON_CART FOREIGN KEY (cart_id) REFERENCES cart (id);

